### ISSUE TITLE
Updating UI and Adding some UI content

### ISSUE THREAD

**Issue by priyamaggarwal18** [darshjain/darshjain.github.io#17]
Hi @darshjain I would love to take on the UI part of your portfolio.so please assign this to me

The things that I will add are: 
1. Add a Typewriter effect on home page
2. replace social icons with some eye catchy icons
3. add further html like the navbar and different sections in your portfolio
4. make a fully responsive and eye-catching UI.

**Comment by darshjain** [comment]
Hey @priyamaggarwal18 , You can do the following on my page
1. Add the Typewritter effect
2. Dont replace social icons
3. For this, i am actually working on a different repo altogether, the current one just serves as a link tree, for these sections you can work on https://github.com/darshjain/portfolio-website 
4. you can do it

**Comment by darshjain** [comment]
Added labels
